### ISSUE TITLE
"Reduce Strain" is applied even when it equals "No" (Gear Modifier)

### ISSUE THREAD

**Issue by Carl-Hugo** [SkyJedi/RPG-Web-Character-Creator#11]
## Bug report
One of my players was playing around with cybernetics, and we noticed that choosing `No` for `Reduce Strain` in a piece of `Gear` does nothing.

**Actual Result:** the strain modifier is applied even when `No` is selected.

**Expected result:** the strain modifier should not be applied when `No` is selected.

## Test data
- Name: Cybernetic Arm, Mod V
- Encumbrance: 0
- Price: 10000
- Description: Arm replacement; +1 Brawn
- Setting: All
- Modifier: Yes
- Attribute: Brawn
- Reduce Strain: No
- Special Qualities: 

### Exported data:

```json
[
    {
        "customData": {
            "customGear": {
                "cyberneticArmModV": {
                    "description": "Arm replacement; +1 Brawn\n",
                    "encumbrance": 0,
                    "modifier": { "Brawn": 1 },
                    "name": "Cybernetic Arm, Mod V",
                    "price": 10000,
                    "qualities": {},
                    "setting": ["All"]
                }
            }
        }
    }
]
```

### Piece of Gear
![image](https://user-images.githubusercontent.com/5885505/49053392-f537fc00-f1bd-11e8-8578-ea369449a0db.png)

### Not carried
![image](https://user-images.githubusercontent.com/5885505/49053452-2a444e80-f1be-11e8-96b3-93f5821d457f.png)

### Carried
![image](https://user-images.githubusercontent.com/5885505/49053463-3203f300-f1be-11e8-98d1-cb99077deef7.png)

---

Thanks for taking the time to build this tool!

**Comment by SkyJedi** [comment]
gasp!  What a detailed bug report thank you!

**Comment by Carl-Hugo** [comment]
Well, I ask people not to tell me "N feature does not work" but to describe the problem instead. I believe that taking a few minutes to fill out a complete bug report is faster than me trying to fix it (using React). Moreover, it allows you to invest your time in adding new features or relaxing at home (or whatever you want to do) instead of digging through my issue, trying to figure out what I did or did not do :wink:

That said you are welcome

---

Side note, if you didn't know, you can create issue's template(s) that people can use when opening issues. You could add all the necessary section making them think about it. The new issue page would look similar to this: 

![image](https://user-images.githubusercontent.com/5885505/49084333-28f63e80-f21d-11e8-8351-369a77eccc6c.png)

Then the issue would get auto-filled like this:

![image](https://user-images.githubusercontent.com/5885505/49084384-52af6580-f21d-11e8-965e-7949ebb2f957.png)

And it is just markdown (takes like 2 minutes to setup).

**Comment by SkyJedi** [comment]
Alrighty, making the items now works properly.  (i think)  Youll have to go and edit existing items and select "yes" or "no" and they will function correctly.  Thanks for the bug report and the advice!

**Comment by Carl-Hugo** [comment]
Great thanks for the quick fix! I will try that out later.

**Comment by Carl-Hugo** [comment]
Now, when `Reduce Strain` equals `No`, the modifier is simply not applied to the attribute (well nothing happens).

## With `yes`
![image](https://user-images.githubusercontent.com/5885505/49114797-14d72f00-f267-11e8-8f29-b951e6526668.png)

![image](https://user-images.githubusercontent.com/5885505/49114786-0e48b780-f267-11e8-8b83-ebdb02acc307.png)

## With `no`
![image](https://user-images.githubusercontent.com/5885505/49114666-c4f86800-f266-11e8-94f0-df89a8179fa7.png)

![image](https://user-images.githubusercontent.com/5885505/49114656-be69f080-f266-11e8-9b00-8056b17389df.png)

**Comment by SkyJedi** [comment]
UGH, i know what i did.  i'll fix it up when i get a minute

**Comment by SkyJedi** [comment]
Should be fixed now!

**Comment by Carl-Hugo** [comment]
Thanks, I will look into it later

**Comment by Carl-Hugo** [comment]
Looks fixed indeed, thanks (closing the issue).
