### ISSUE TITLE
Grit talent not increasing strain threshold

### ISSUE THREAD

**Issue by egonil** [SkyJedi/RPG-Web-Character-Creator#14]
**Describe the bug**
Taking the Grit talent does not increase the strain threshold.

**To Reproduce**
1. Create New character. Scroll down to Talents section.
2. Click on a new talent box. Select Grit
3. Scroll up to Attributes section
4. See that the Strain Threshold hasn't changed.

**Expected behavior**
Taking the Grit talent should increase the strain threshold by one.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 71

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 9
 - Browser: stock
 - Version: 71 

**Additional context**
Selecting an Archetype isn't needed and makes no difference that I've seen.
Selecting Toughened does increase the woundThreshold.
Creating a custom talent that increases the strainThreshold does increase the strainThreshold when taken.

**Comment by SkyJedi** [comment]
https://github.com/SkyJedi/RPG-Web-Character-Creator/commit/fbcbec4279639356bfd8ecde4f34874c09d9216b
