### ISSUE TITLE
prerequisite talents should be required

### ISSUE THREAD

**Issue by egonil** [SkyJedi/RPG-Web-Character-Creator#15]
**Describe the bug**
prerequisite talents should be required

**To Reproduce**
1. Create a new character.
2. Add two Tier 1 talents. Do not chose Defensive Sysops as one of them.
3. Click on the now available Tier 2 talent.
4. Select Defensive Sysops (Improved) from list. Enter to add it.

**Expected behavior**
Prerequisites should be required.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version : 71

**Smartphone (please complete the following information):**

**Additional context**
Defensive Sysops is just an example. The others talents I spot checked, like Parry (Improved), don't require prerequisites either.

**Comment by SkyJedi** [comment]
https://github.com/SkyJedi/RPG-Web-Character-Creator/commit/9df8b4a4141fe0185d6e21e6870de50022bf79fa
