### ISSUE TITLE
add mechanism to switch from initial character creation to spending earned experience

### ISSUE THREAD

**Issue by egonil** [SkyJedi/RPG-Web-Character-Creator#16]
**Is your feature request related to a problem? Please describe.**
Characteristics can be modified at any time.

**Describe the solution you'd like**
When I am done with the initial creation of a character, I should be able to toggle a setting that changes from creation mode to advancement mode.
In advancement mode, characteristics, archetype, and career, should all be locked.

**Describe alternatives you've considered**
"Just remember not to change things that aren't supposed to be changed."

**Additional context**

**Comment by SkyJedi** [comment]
lemme think about this one for a while.  i think i'd have to change a few major things before i could implement this.  I'll put it on the wishlist though

**Comment by SkyJedi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [character creation lock](https://trello.com/c/Kj6sF5eF/270-character-creation-lock)
