### ISSUE TITLE
Custom Data > `Settings` is greyed out to me unable to reference at all

### ISSUE THREAD

**Issue by dlwest72** [SkyJedi/RPG-Web-Character-Creator#20]
**Describe the bug**
Custom Data > `Settings` is greyed out to me unable to reference at all.

**To Reproduce**
1. Go to https://genesysemporium.com/ as dlwest72@gmail.com
2. Click on Custom Data > `Settings` is greyed out to me unable to reference at all

**Expected behavior**
Should be able to access and modify Settings.

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: HIgh Sierra 10.13.6 
 - Browser Chrome Version 71.0.3578.98 (Official Build) (64-bit)
![settings](https://user-images.githubusercontent.com/4602770/52182167-e83c1800-27bf-11e9-99fe-14c94b89ec7e.jpg)

**Comment by SkyJedi** [comment]
Settings have been removed, new system pending

**Comment by dvbuntu** [comment]
I was briefly able to add a setting today, but then it greyed out again when restarting.  Is this feature still in the works?
