### ISSUE TITLE
The encumbrance is displayed inverted and could be confusing.

### ISSUE THREAD

**Issue by Carl-Hugo** [SkyJedi/RPG-Web-Character-Creator#6]
## Description
The encumbrance is displayed inverted and could be confusing.

It is displayed in the `max/current` format. Ex.: `6/5` where `5` is the character current encumbrance level and `6` his maximum.

## Expectation
I was more expecting a `current/max` display. Ex.: `5/6` would mean that the character has `5` encumbrance due to gear out of a maximum of `6`.

## Additional notes
I was wondering if you had any reason to display the encumbrance this way.

If you are interested in flipping it from `max/current` to `current/max`, I don't mind making the change and creating a PR to help you out.

**Comment by SkyJedi** [comment]
you're correct that is crazy confusing.  I'll update that

**Comment by SkyJedi** [comment]
https://github.com/SkyJedi/RPG-Web-Character-Creator/commit/7b1ef15d451056b9f91fb52e676fb0094e9c68fb

done
